service: 'api'
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: sbx

plugins:
  - serverless-esbuild

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
