service: 'api'
frameworkVersion: '3'

provider:
  name: 'aws'
  runtime: 'nodejs18.x'
  profile: 'sbx'

plugins:
  - 'serverless-esbuild'
  # - 'serverless-domain-manager' #TODO: add custom domain for api.

functions:

  RegistrationFormSubmitted:
    handler: 'src/functions/auth/RegistrationFormSubmitted/RegistrationFormSubmitted.handler'

  # api:
  #   handler: 'index.handler'
  #   events:
  #     - httpApi:
  #         path: '/'
  #         method: 'get'
